# Examples: https://codefresh.io/docs/docs/yaml-examples/examples
#
# CF_BRANCH value is auto set when pipeline is triggered
# - Learn more at codefresh.io/docs/docs/codefresh-yaml/variables

version: '1.0'
stages:
  - clone
  - build
  - push

steps:
  clone:
    title: 'Cloning repository'
    type: git-clone
    stage: clone
    repo: 'ChristianOellers/CLI-Strike'
    revision: '${{CF_BRANCH}}'
    git: github

  build:
    title: 'Building Docker image'
    type: build
    stage: build
    tag: '${{CF_BRANCH_TAG_NORMALIZED}}'
    image_name: cli-strike
    working_directory: ${{clone}}
    dockerfile: Dockerfile
    registry: dockerhub

  push:
    title: 'Pushing Docker image'
    type: push
    stage: push
    tag: 'latest'
    candidate: ${{build}}
    registry: dockerhub
